<?php

namespace App\Services;

use App\Models\Module;
use App\Models\Training;
use App\Models\TrainingSession;
use App\Repositories\TrainingRepository;
use App\Traits\UploadFileTrait;
use Exception;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

/**
 * class TrainingService
 */
class TrainingService
{
    use UploadFileTrait;

    protected TrainingRepository $trainingRepository;

    public function __construct(TrainingRepository $trainingRepository)
    {
        $this->trainingRepository = $trainingRepository;
    }

    public function getAll(Request $request)
    {
        $filters = $request->only([
            'title', 'training_type', 'status', 'responsible_id',
            'target_audience', 'cabinet_id', 'is_active', 'per_page',
        ]);
        return $this->trainingRepository->withFilters($filters);
    }

    /**
     * @throws ModelNotFoundException
     */
    public function find(int $id): Training
    {
        return $this->trainingRepository->find($id);
    }

    /**
     * Create training + modules + sessions (ids generated by observers).
     */
    public function createWithChildren(array $data, Request $request): Training
    {
        return DB::transaction(function () use ($data, $request) {
            // training attachments
            if ($request->hasFile('attachments')) {
                $attachmentPaths = [];
                foreach ((array) $request->file('attachments') as $file) {
                    $attachmentPaths[] = $this->uploadPublicFile($file, 'trainings/attachments');
                }
                $data['attachments'] = $attachmentPaths;
            }

            $data['created_by_id'] = $data['created_by_id'] ?? Auth::id();

            /** @var Training $training */
            $training = $this->trainingRepository->create($data);

            // modules + sessions
            $modules = Arr::get($data, 'modules', []);
            foreach ($modules as $i => $modulePayload) {
                $module = $this->createOrUpdateModule($training, $modulePayload, $request, $i);

                $sessions = Arr::get($modulePayload, 'sessions', []);
                foreach ($sessions as $j => $sessionPayload) {
                    $this->createOrUpdateSession($training, $module, $sessionPayload, $request, $i, $j);
                }
            }

            return $training;
        });
    }

    /**
     * Update training + modules + sessions (ids generated by observers).
     */
    public function updateWithChildren(int $id, array $data, Request $request): Training
    {
        return DB::transaction(function () use ($id, $data, $request) {
            /** @var Training $training */
            $training = $this->trainingRepository->find($id);

            // attachments merge/remove
            $currentAttachments = (array) ($training->attachments ?? []);

            $removedAttachments = (array) $request->input('removed_attachments', []);
            if (!empty($removedAttachments)) {
                foreach ($removedAttachments as $pathToRemove) {
                    $this->deletePublicFile($pathToRemove);
                    $currentAttachments = array_values(array_diff($currentAttachments, [$pathToRemove]));
                }
            }

            if ($request->hasFile('attachments')) {
                foreach ((array) $request->file('attachments') as $file) {
                    $currentAttachments[] = $this->uploadPublicFile($file, 'trainings/attachments');
                }
            }

            $data['attachments']   = $currentAttachments;
            $data['created_by_id'] = $training->created_by_id ?? Auth::id();

            $training = $this->trainingRepository->update($data, $id);

            // reconcile modules + sessions
            $incomingModules = Arr::get($data, 'modules', []);
            $existingModules = $training->modules()->with(['sessions'])->get()->keyBy('id');

            foreach ($incomingModules as $i => $modulePayload) {
                // soft-delete module
                if (!empty($modulePayload['id']) && !empty($modulePayload['deleted'])) {
                    $module = $existingModules->get((int) $modulePayload['id']);
                    if ($module) {
                        $module->delete();
                    }
                    continue;
                }

                // upsert module
                $module = $this->createOrUpdateModule($training, $modulePayload, $request, $i);

                // sessions under this module
                $incomingSessions = Arr::get($modulePayload, 'sessions', []);
                $existingSessions = $module->sessions()->get()->keyBy('id');

                foreach ($incomingSessions as $j => $sessionPayload) {
                    // soft-delete session
                    if (!empty($sessionPayload['id']) && !empty($sessionPayload['deleted'])) {
                        $existing = $existingSessions->get((int) $sessionPayload['id']);
                        if ($existing) {
                            $existing->delete();
                        }
                        continue;
                    }

                    // upsert session
                    $this->createOrUpdateSession($training, $module, $sessionPayload, $request, $i, $j);
                }
            }

            return $training;
        });
    }

    /**
     * Upsert module; ignore any client-provided 'module_id' (observer generates).
     */
    private function createOrUpdateModule(Training $training, array $payload, Request $request, int $i): Module
    {
        // Select allowed fields (explicitly exclude 'module_id')
        $moduleFields = Arr::only($payload, [
            'title',
            'pedagogical_objectives',
            'trainer_id',
            'competency_grid_id',
            'total_duration',
            'formation_type',
            'evaluation_planned',
            'status',
        ]);

        // Hard guard if present by mistake
        unset($moduleFields['module_id']);

        $moduleFields['training_id']   = $training->id;
        $moduleFields['created_by_id'] = $moduleFields['created_by_id'] ?? Auth::id();

        /** @var Module|null $module */
        $module = null;
        if (!empty($payload['id'])) {
            $module = Module::query()
                ->where('training_id', $training->id)
                ->find((int) $payload['id']);
        }

        // Merge pedagogical supports
        $existingSupports = (array) ($module?->pedagogical_supports ?? []);
        $providedSupports = (array) Arr::get($payload, 'pedagogical_supports', []); // keep string paths

        $uploadedSupports = [];
        $files = $request->file("modules.$i.pedagogical_supports");
        if ($files) {
            foreach ((array) $files as $file) {
                $uploadedSupports[] = $this->uploadPublicFile($file, 'modules/supports');
            }
        }

        $removed = (array) Arr::get($payload, 'removed_supports', []);
        if (!empty($removed)) {
            foreach ($removed as $path) {
                $this->deletePublicFile($path);
                $existingSupports = array_values(array_diff($existingSupports, [$path]));
            }
        }

        $finalSupports = array_values(array_unique(array_merge(
            array_filter($providedSupports, fn ($p) => is_string($p) && $p !== ''),
            $existingSupports,
            $uploadedSupports
        )));

        $moduleFields['pedagogical_supports'] = $finalSupports;

        if ($module) {
            $module->update($moduleFields);
        } else {
            $module = Module::create($moduleFields); // observer will set module_id
        }

        return $module;
    }

    /**
     * Upsert session; ignore any client-provided 'session_identifier' (observer generates).
     */
    // app/Services/TrainingService.php


private function createOrUpdateSession(
    Training $training,
    Module $module,
    array $payload,
    Request $request,
    int $i,
    int $j
): TrainingSession {
    // DO NOT accept 'session_identifier' from payload (observer will generate it)


    $sessionFields = \Illuminate\Support\Arr::only($payload, [
        // 'session_identifier',         // <-- excluded on purpose
        // 'training_group_id',          // <-- will be auto-filled below
        'animator_type',                // required by migration (morphs)
        'animator_id',                  // required by migration (morphs)
        'session_date',
        'start_time',
        'end_time',
        'planned_duration_hours',
        'site_id',
        'session_type',                 // 'Theorique' | 'Pratique' | 'Evaluation'
        'presence_registered',
        'observations',
        'status',                       // 'Planifiée' | 'Réalisée' | 'Reportée' | 'Annulée'
    ]);


    $sessionFields['training_id']   = $training->id;
    $sessionFields['module_id']     = $module->id;
    $sessionFields['created_by_id'] = $sessionFields['created_by_id'] ?? \Illuminate\Support\Facades\Auth::id();


    // IMPORTANT: DB requires NOT NULL for training_group_id → auto-pick/create one
    $sessionFields['training_group_id'] = $payload['training_group_id']
        ?? $this->pickTrainingGroupId($training);


    /** @var TrainingSession|null $session */
    $session = null;
    if (!empty($payload['id'])) {
        $session = TrainingSession::query()
            ->where('training_id', $training->id)
            ->where('module_id', $module->id)
            ->find((int) $payload['id']);
    }


    if ($session) {
        $session->update($sessionFields);
    } else {
        $session = TrainingSession::create($sessionFields);
    }


    return $session;
}


/**
 * Choose or create a TrainingGroup so training_group_id is never NULL.
 * Adjust the fields ('title', 'status', etc.) to your TrainingGroup fillables.
 */
private function pickTrainingGroupId(Training $training): int
{
    // 1) reuse first existing group if any
    $group = $training->trainingGroups()->first();
    if ($group) {
        return $group->id;
    }


    // 2) else create a default group
    $group = $training->trainingGroups()->create([
        'title'  => 'Groupe A',
        'status' => 'active', // adapt to your TrainingGroup schema if different
        // add any required columns here…
    ]);


    return $group->id;
}


    public function delete(int $id): int
    {
        return $this->trainingRepository->delete($id);
    }

    public function bulkDestroy(array $ids): int
    {
        return $this->trainingRepository->bulkDelete($ids);
    }

    public function restore(int $id): Training
    {
        try {
            return $this->trainingRepository->restore($id);
        } catch (Exception $e) {
            abort(409, $e->getMessage());
        }
    }
}
